layout_spectrum: 0
typography_spectrum: 0
color:
  saturation: 0.8261649
  lightness: 0.9103943
  brandStrength: 0.3970873
  brandColors:
    - '#B1B0AE'
    - '#DCDEDB'
    - '#454640'
    - '#131418'
    - '#7B7B7B'
  rhythmicContrast: 0.7526882
name: BentoBox
